recipe: default.v1
language: en

pipeline:
- name: WhitespaceTokenizer
  intent_tokenization_flag: true
  intent_split_symbol: "+"
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: word
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 5
- name: DIETClassifier
  epochs: 126
  use_masked_language_model: true
  constrain_similarities: true
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.5518021400481513
  ambiguity_threshold: 0.1979748412038714

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 9
  epochs: 98
- name: TEDPolicy
  max_history: 5
  epochs: 77
  split_entities_by_comma:
    allergen: true
  constrain_similarities: true

assistant_id: 20230505-140653-annoying-grenade
