version: '3.0'

services:
  rasa:
    container_name: rasa
    build: .
    image: rasa/rasa:3.5.6-full
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./:/app/"

  action:
    container_name: action
    build:
      context: ./actions
      dockerfile: Dockerfile
    image: rasa/rasa-sdk:3.5.1
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./actions:/app/actions"
    depends_on:
      - rasa

networks: {rasa-network: {}}