version: "3.1"
nlu:
- intent: faq/low_carb
  examples: |
    - What are some low-carb meal options?
    - Are there any low-carb bread alternatives?
    - Can you recommend low-carb snacks?
    - How can I reduce my carbohydrate intake?
    - What are the benefits of a low-carb diet?
- intent: faq/eating_disorder
  examples: |
    - How can i stop restricting my food intake?
    - How can I stop purging?
    - How can i develop a healthier relationship with food?
    - How can i overcome emotional eating habits?
    - how does eatign disorder affect me?
    - what to eat as a person with eating disorder?
    - What are the signs and symptoms of an eating disorder?
- intent: faq/cholesterol
  examples: |
    - what can i eat if i have cholesterol?
    - What is cholesterol, and how does it impact my health?
    - Are there any specific foods that can help improve cholesterol levels?
    - How does dietary cholesterol impact my blood cholesterol levels?
    - Can you provide guidance on cholesterol-lowering medications?
    - having cholesterol, what should i eat?
    - What are the differences between LDL and HDL cholesterol?
    - what do you recommend for a person with high cholesterol?
- intent: faq/ask_is_bot
  examples: |
    - am i talking to a bot?
    - am i talking to a human?
    - are you a real person or a computer?
    - am i taking to a chatbot or a real person
    - are you a bot
    - you are human
    - is you a real person?
    - are you an ai
    - are you an actual person?
- intent: faq/diet_options
  examples: |
    - Can you tell me about different types of diets?
    - what r the diet plans you offer
    - What are some popular diet options?
    - what are the meal plans you provide?
    - wat are the meal plans you have
    - what are the diet plans available?
    - what r the diet plans?
    - what are the diet options?
    - can you give me a list of all diets that you have?
- intent: faq/water
  examples: |
    - how much water should i drink daily
    - how much liters should a girl drink?
    - how much water should a man drink daily?
    - water consumption
    - what is the healthy amount of water to drink?
    - how much water should i drink?
    - how much water shoudl i drink?
    - water intake recommendation
    - how much liquid do i need to drink to be healthy
- intent: faq/low_fat
  examples: |
    - What are the benefits of a low-fat diet?
    - How can I reduce my fat intake?
    - What are some low-fat meal options?
    - What are some low-fat food options?
    - Are there any low-fat bread alternatives?
    - Can you suggest low-fat dairy alternatives?
    - How can I reduce the fat content in my meals?
    - Are there any low-fat cooking techniques I should use?
    - what are some low fat food
- intent: faq/high_protein
  examples: |
    - i need food with a lot of protein
    - What are some high protein food recommendations?
    - what meals are high in protein?
    - top 5 food with high protein
    - Can you give me examples of food with high protein?
    - can you give me example of food with high protein?
    - Can you suggest some high protein recipe
    - Are there any protein-rich snacks I can have?
    - How can I increase my protein intake?
    - high protein food
    - What meals are high in protein?
    - food high in protein
- intent: greet
  examples: |
    - hey dude
    - hello
    - moin
    - good morning
    - goodevening
    - hey
    - hey there
    - good evening
    - let's go
    - goodmorning
    - hi
- intent: deny
  examples: |
    - never
    - none
    - no way
    - i dont think so
    - no thanks
    - not at all
    - nah
    - non
    - nope
    - no
    - not really
- intent: inform_no_allergens
  examples: |
    - no allergies
    - btw i dont have any allegies anymore
    - allergies: none
    - no dietary restrictions
    - correction: no allergies
    - no allergy
    - i dont have any food allergies
    - i dont have allergies!
    - i dont have any allergies
    - can you correct the fact that i do not have any allergies
    - no allergen
- intent: get_started
  examples: |
    - lets get started
    - can you help me use the chatbot
    - Let's get started!🤩
    - how do i start?
    - what can i do?
    - how do i proceed
    - what can you do?
    - how do i get started
    - what is your purpose
    - what must i do?
    - what must i say?
    - what can i say
- intent: thanks
  examples: |
    - tanku
    - thanx
    - thank you so much
    - thanks for the help
    - thank you
    - thks
    - tanks
    - sanks
    - thanks!
    - tenks
    - fanks
    - thank again
    - ty
- intent: inform_no_diet
  examples: |
    - i dont have a diet
    - balanced
    - i dont have a specific diet
    - idk
    - I prefer a balanced diet that includes a variety of food groups.
    - i dont know
    - nothing specific
    - i dont know tbh
    - no preference
    - im not following any specific diet, but i want a healthy and sustainable meal plan.
    - whatever
    - i do not have a specific diet yet
    - i dont have a preference
- intent: inform_activity_level
  examples: |
    - [2](activity_level)
    - activity level: [2](activity_level)
    - activity: [1](activity_level)
    - [one]{"entity": "activity_level", "value": "1"}
    - [two]{"entity": "activity_level", "value": "2"}
    - [3](activity_level)
    - [three]{"entity": "activity_level", "value": "3"}
    - [five]{"entity": "activity_level", "value": "5"}
    - [4](activity_level)
    - [0](activity_level)
    - [3](activity_level) /5
    - [1](activity_level) or [2](activity_level)
    - [7](activity_level) /10
    - [1](activity_level)
    - [3](activity_level) maybe
    - [5](activity_level)
- intent: affirm
  examples: |
    - yess
    - cont
    - ye
    - ofc
    - okay
    - tes
    - continu
    - yes
    - of course
    - good
    - ok
    - affirm
    - yeah
    - yep
    - all good
    - yea
    - fine
- intent: maintain_weight
  examples: |
    - i dont want to change my weight
    - im good with my weight
    - Could you provide some examples of a typical day's meal plan for weight maintenance, including breakfast, lunch and dinner?
    - Are there specific portion sizes or calorie ranges I should aim for to sustain my current weight?
    - i want a [keto](diet) diet to maintain my weight
    - i want to keep my weight
    - nothing
    - i want to maintain my weight with a [vegetarian](diet) diet
    - my weight is good
    - my weight is fine
    - weight is good
    - I'm happy with my weight, but I'd like to eat healthier. Can you help me with that?
    - i want a healthy diet to stay at my current weight
    - I'm happy with my current weight and just want to maintain it.
    - Could you provide me with a balanced diet plan that ensures I maintain my weight without any significant fluctuations?
    - my goal is to maintain my weight
    - i need to balance my weight
    - goal: maintain weight
- intent: inform_allergens
  examples: |
    - [dairy](allergen) products
    - [sesame](allergen) and [egg](allergen)
    - [sesame](allergen) and [tree nut](allergen)
    - [eggs]{"entity": "allergen", "value": "egg"} and [peanut](allergen)
    - im allergic to [peanut](allergen)
    - [egg](allergen) and [sesame](allergen)
    - no [fish](allergen) and [egg](allergen)
    - [wheat](allergen)
    - [sulfite](allergen)
    - [grain](allergen)
    - [sesame](allergen) [wheat](allergen) and [peanut](allergen)
    - [nuts](allergen) and [egg](allergen)
    - im allergic to [eggs](allergen)
    - [egg](allergen)
    - im allergic to [sulfite](allergen)
    - [seafood](allergen)
    - [sesame](allergen) and [soy](allergen)
    - [brocoli](allergen)
    - [mollusks](allergen)
    - [peanuts](allergen) allergies
    - [tree nut](allergen)
    - i cant eat [nuts](allergen)
- intent: ask_diet_plan
  examples: |
    - can i get another diet plan please
    - I'm looking for a personalized diet plan. Can you create a meal plan tailored to my specific needs and goals?
    - can i get a diet plan
    - give me a planned meal
    - I need help with meal planning. Can you assist me in creating a well-balanced diet plan?
    - hello there how do i get my meal plan?
    - can i have a customized diet meal plan
    - i want a diet plan
    - Can you suggest some healthy recipes or resources I can use to supplement a diet plan?
    - Can you suggest a sample diet plan that aligns with my dietary preferences and health goals?
    - hello i want a diet plan plz
    - What are the food I should consider when developing a diet plan for myself?
    - Could you provide me with a comprehensive diet plan that includes breakfast, lunch, dinner, and snacks?
    - How can I create a healthy meal plan?
    - Create a Meal Plan🍽️
    - i need a meal plan
    - Create another Meal Plan🍽️
    - What should a balanced meal consist of?
    - How can I meal prep for the week?
    - help me to creat a diet
    - i want another diet
    - i need a diet
    - can you recomand me a diet
- intent: gain_weight
  examples: |
    - to be bigger
    - im currently underweight
    - i want to gain weight fast
    - i want a [vegetarian](diet) diet plan to gain muscles mass
    - im trying to gain weight. What are some healthy ways to do so?
    - i want to gain muscles
    - gain weight
    - I'm trying to gain weight.
    - i need to gain weight fast
    - i want to be heavier
    - i want som more weight
    - i am too skinny
    - bigger muscles
    - i want to gain weight
    - i want to gain muscle mass
    - im hoping to gain 5 pounds of muscle
    - how do i gain weight
    - How can I maintain a balanced diet while still focusing on gaining weight?
    - my goal is to gain weight
    - i want a [paleo](diet) meal plan to gain weight
    - Could you suggest some high-calorie foods or snacks that I can incorporate into my diet?
    - can i get more mass
    - i want a [high protein](diet) diet to gain mass
- intent: lose_weight
  examples: |
    - give me a [keto]{"entity": "diet", "value": "ketogenic"} diet to lose weight
    - im overweight
    - can you give me a diet plan to lose weight fast
    - Can you recommend some effective strategies for weight loss?
    - i want a [low carb](diet) diet for weight loss
    - im obese
    - I'm trying to lose weight.
    - how to burn fat
    - lose weight
    - help me loss weight
    - I'm looking for a diet that can help me lose weight.
    - how to lose weight?
    - how can i reduce my weight?
    - I'm tired of being overweight and I'm ready to make a change
    - i need a [keto](diet) meal plan to lose weight
    - my goal is to loose weight
    - loss fat quickly
    - i want a [keto](diet) to lose weigh
    - i want to diet to help me lose weight
    - i want to lse weight
    - i want a [vegetarian](diet) diet to lose weight
    - Could you provide me with a weight loss meal plan or some guidance on creating one?
    - i want to burn all my fat
    - I'm trying to lose weight. What are some healthy ways to do so?
    - im too fat
    - I'm looking to lose weight.
    - i want a [paleolithic]{"entity": "diet", "value": "paleo"} diet to loss weight
    - i want to lose 5 kg
    - i need a [vegan](diet) diet to lsoe weight
    - i dont want to be fat
- intent: inform_diet
  examples: |
    - [dash](diet) diet
    - I'm looking for a [vegan](diet) diet.
    - [pescatarian](diet)
    - i will need a [whole30](diet) diet
    - [keto]{"entity": "diet", "value": "ketogenic"} diet
    - [intermittent fasting](diet)
    - i want a [keto]{"entity": "diet", "value": "ketogenic"} diet
    - [veg]{"entity": "diet", "value": "vegetarian"}
    - [whole30](diet) diet
    - I'm looking for a [vegan](diet) diet plan.
    - [keto]{"entity": "diet", "value": "ketogenic"}
    - i want a [veg]{"entity": "diet", "value": "vegetarian"} diet
    - im looking for a [paleo](diet) diet
    - [Mediterranean](diet) Diet
    - i [dont eat gluten]{"entity": "diet", "value": "gluten free"}
    - [Dietary Approaches to Stop Hypertension]{"entity": "diet", "value": "dash"}
    - [paleo](diet) diet
    - [non-veg](diet)
    - i am [vegan](diet)
    - [veggie]{"entity": "diet", "value": "vegetarian"}
    - [greek](diet) diet
    - i want a [primal](diet) diet type
    - I'm looking for a diet that's based on the [Mediterranean](diet) diet. I've heard it's good for my heart health
    - I'm looking for a diet that's based on whole foods and i think the [paleo](diet) diet might be a good fit.
    - i'm interested in the [plant-based](diet) diet because I think it's healthier for me.
    - I've been reading about [intermittent](diet) fasting and I'm wondering if it would be a good option for me
    - im looking for a [mediteranean]{"entity": "diet", "value": "mediterranean"} diet
    - [no gluten]{"entity": "diet", "value": "gluten free"}
    - [primal](diet) diet
    - maybe a diet called [primal](diet) diet
- intent: inform_details
  examples: |
    - heihgt of [1m69](height)
    - age = [20](age)
    - age : [34](age)
    - [65kg](weight)
    - [1m 80](height) [69kg](weight) [45](age) [male](gender)
    - im arounnd [5 feet 10 inches](height), weigh [200 pounds](weight), [non-binary](gender), and [22 years](age) old
    - height : [1m 64cm](height)
    - [1m 64](height)
    - [182cm](height)
    - [179cm](height) [70kg](weight) [39](age) [female](gender)
    - yes and im a [19](age) years old [girl]{"entity": "gender", "value": "female"}
    - [1m75](height) [69kg](weight) [22](age) [male](gender)
    - [168cm](height) , [65kg](weight) , [40](age) , [female](gender)
    - [175cm](height) and [75kg](weight)
    - im [168cm](height) and i weigh [60.5kg](weight)
    - im [168cm](height) tall and weighs [61.5kg](weight)
    - im [1m60](height), i weigh [60kg](weight) i have [23](age) and im a [girl]{"entity": "gender", "value": "female"}
    - [155cm](height) and [55kg](weight) and [25yo]{"entity": "age", "value": "25"}
    - [80kg](weight)
    - age [34](age)
    - im a [21yo]{"entity": "age", "value": "21"} [male](gender)
    - [1m70](height) and [70kg](weight) and [20](age) years old
    - im [1m82](height)
    - weight : [75kg](weight)
    - im a [43yr](age) old [man]{"entity": "gender", "value": "male"} and im [1m70](height) and [70.4kg](weight)
    - my age is [25](age) years old
    - [1m75](height) [66kg](weight) [25yo]{"entity": "age", "value": "25"} [male](gender)
    - im [43](age) and [170cm](height) [52kg](weight)
    - im [1m69](height) i weigh [45kg](weight) i have [21yo](age) and im a [girl]{"entity": "gender", "value": "female"}
    - gender [male](gender)
- synonym: gluten free
  examples: |
    - dont eat gluten
    - no gluten
- synonym: vegetarian
  examples: |
    - veggie
    - veg
    - vege
    - vegetarian
- synonym: ketogenic
  examples: |
    - keto
    - keto-friendly
    - keto friendly
- synonym: mediterranean
  examples: |
    - mediteranean
- synonym: dash
  examples: |
    - Dietary Approaches to Stop Hypertension
- synonym: egg
  examples: |
    - eggs
    - egg-less
    - omlete
- synonym: '25'
  examples: |
    - 25yo
- synonym: '18'
  examples: |
    - 18years
- synonym: female
  examples: |
    - girl
    - f
    - lady
    - woman
- synonym: male
  examples: |
    - man
    - m
    - boy
    - gentleman
- synonym: '45'
  examples: |
    - 45yo
- synonym: '21'
  examples: |
    - 21yo
- synonym: '1'
  examples: |
    - one
- synonym: '2'
  examples: |
    - two
- synonym: '3'
  examples: |
    - three
- synonym: '4'
  examples: |
    - four
- synonym: '5'
  examples: |
    - five
- synonym: paleo
  examples: |
    - paleolithic
    - paleo friendly
    - paleo
- synonym: dairy
  examples: |
    - dairy
    - milk
    - lactose intolerant
- synonym: gluten
  examples: |
    - cereal
    - grass
    - durum
    - semolina
    - spelt
- synonym: peanut
  examples: |
    - nut
- synonym: seafood
  examples: |
    - fish
    - crustaceans
    - mollusks
    - marine food
    - prawn
    - salmon
    - sardines
    - tuna
    - carp
- synonym: shellfood
  examples: |
    - shrimp
    - crayfish
    - crab
    - lobster
    - clams
    - mussel
    - oyster
- synonym: tree nut
  examples: |
    - almond
    - walnut
    - cashew
- regex: activity_level
  examples: |
    - [1-5]
- regex: age
  examples: |
    - \d{1,3}
